# All pmd:codesUsed must have a label (for PMD)
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?code
WHERE {
  GRAPH <http://gss-data.org.uk/graph/hmrc-uk-trade-in-goods-statistics-by-business-characteristics-2015> {
    ?cs <http://publishmydata.com/def/qb/codesUsed>/skos:member ?code
  }
  FILTER NOT EXISTS {
    ?code rdfs:label ?label
  }
} LIMIT 1000
