PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX csvw:  <http://www.w3.org/ns/csvw#>
PREFIX qb:    <http://purl.org/linked-data/cube#>

DELETE { ?old ?p ?o }
INSERT { ?new ?p ?o }
WHERE {
  ?old a csvw:Table ;
     ?p ?o .
  [] qb:dataSet ?new
}
